name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - uses: actions/checkout@v5

    - uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: "true"

    - name: Install
      run: |
        uv pip install --group test -e .

    - name: Run tests
      if: ${{ !((matrix.python-version == '3.14') && (matrix.os == 'ubuntu')) }}
      run: uv run pytest --color=yes -v tests/

    - name: Check code coverage
      if: ${{ (matrix.python-version == '3.14') && (matrix.os == 'ubuntu') }}
      run: |
        uv run coverage run -m pytest tests/
        uv run coverage report --show-missing #--fail-under=100
